package com.freiberg.model;

public enum MessageType {
    CONVERSATION_DATA_REQUEST,
    CONVERSATION_DATA_RESPONSE,
    CONTACTS_RESPONSE,
    DIALOGS_PREVIEWS_RESPONSE,
    USER_SEARCH_REQUEST,
    USER_SEARCH_RESULT_RESPONSE,
    CHAT_COMMUNICATION
}
