export enum MessageType {
  CONVERSATION_DATA_REQUEST = 'CONVERSATION_DATA_REQUEST',
  CONVERSATION_DATA_RESPONSE = 'CONVERSATION_DATA_RESPONSE',
  DIALOGS_PREVIEWS_RESPONSE = 'DIALOGS_PREVIEWS_RESPONSE',
  CHAT_ACTIVITY = 'CHAT_ACTIVITY',
  CHAT_COMMUNICATION = 'CHAT_COMMUNICATION',
  USER_SEARCH_REQUEST = 'USER_SEARCH_REQUEST',
  USER_SEARCH_RESULT_RESPONSE = 'USER_SEARCH_RESULT_RESPONSE'
}
